import {Asset} from "./Asset.ts";
import {AssetFactory} from "./AssetFactory.ts";
import {z} from 'zod';

export class AssetCollectionBuilder {

    static build<T>(
        jsonModules: Record<string, unknown>,
        imageModules: Record<string, unknown>,
        schema: z.ZodType<T>,
        imageExtension: string = '.jpg'
    ): Asset<T>[] {
        const assets: Asset<T>[] = [];

        for (const jsonPath in jsonModules) {
            // Change e.g., 34_900px.json to 34_900px.jpg
            const imagePath = jsonPath.replace('.json', imageExtension);

            // Fetching the raw JSON object generated by Vite
            const rawMeta = jsonModules[jsonPath];

            // VALIDATION: If JSON lacks e.g., 'building_height' as a number,
            // Zod will throw an error here (ZodError) and stop loading the level.
            const parsedMeta = schema.parse(rawMeta);

            const imageUrl = imageModules[imagePath] as string;

            if (imageUrl) {
                // Creating a strongly typed asset
                assets.push(AssetFactory.create<T>(imageUrl, parsedMeta));
            } else {
                console.error(`Integrity error: Found ${jsonPath}, but missing image ${imagePath}`);
            }
        }

        return assets;
    }
}
